CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Purchases" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BuyerId" character varying(100) NOT NULL,
    "OfferId" integer NOT NULL,
    "PurchaseDate" timestamp with time zone NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "Status" character varying(50) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Purchases" PRIMARY KEY ("Id")
);

INSERT INTO "Purchases" ("Id", "Amount", "BuyerId", "CreatedAt", "IsActive", "OfferId", "PurchaseDate", "Status", "UpdatedAt")
VALUES (1, 25000.0, 'BUYER001', TIMESTAMPTZ '2026-01-02T09:58:41.163818Z', TRUE, 1, TIMESTAMPTZ '2026-01-02T09:58:41.163818Z', 'Completed', NULL);
INSERT INTO "Purchases" ("Id", "Amount", "BuyerId", "CreatedAt", "IsActive", "OfferId", "PurchaseDate", "Status", "UpdatedAt")
VALUES (2, 32000.0, 'BUYER002', TIMESTAMPTZ '2026-01-02T09:58:41.163818Z', TRUE, 2, TIMESTAMPTZ '2026-01-02T09:58:41.163818Z', 'Pending', NULL);
INSERT INTO "Purchases" ("Id", "Amount", "BuyerId", "CreatedAt", "IsActive", "OfferId", "PurchaseDate", "Status", "UpdatedAt")
VALUES (3, 18500.0, 'BUYER001', TIMESTAMPTZ '2026-01-02T09:58:41.163819Z', TRUE, 3, TIMESTAMPTZ '2026-01-02T09:58:41.163819Z', 'Processing', NULL);

SELECT setval(
    pg_get_serial_sequence('"Purchases"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Purchases") + 1,
        nextval(pg_get_serial_sequence('"Purchases"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260102095841_InitialCreate', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "Purchases" ADD "BuyerIdTemp" integer;


                UPDATE "Purchases" 
                SET "BuyerIdTemp" = CASE 
                    WHEN "BuyerId" = 'BUYER001' THEN 1001
                    WHEN "BuyerId" = 'BUYER002' THEN 1002
                    ELSE 1000 + CAST(SUBSTRING("BuyerId" FROM 6) AS INTEGER)
                END;
            

ALTER TABLE "Purchases" DROP COLUMN "BuyerId";

ALTER TABLE "Purchases" RENAME COLUMN "BuyerIdTemp" TO "BuyerId";

ALTER TABLE "Purchases" ALTER COLUMN "BuyerId" SET NOT NULL;

UPDATE "Purchases" SET "CreatedAt" = TIMESTAMPTZ '2026-01-02T10:24:36.932965Z', "PurchaseDate" = TIMESTAMPTZ '2026-01-02T10:24:36.932965Z'
WHERE "Id" = 1;

UPDATE "Purchases" SET "CreatedAt" = TIMESTAMPTZ '2026-01-02T10:24:36.932965Z', "PurchaseDate" = TIMESTAMPTZ '2026-01-02T10:24:36.932965Z'
WHERE "Id" = 2;

UPDATE "Purchases" SET "CreatedAt" = TIMESTAMPTZ '2026-01-02T10:24:36.932965Z', "PurchaseDate" = TIMESTAMPTZ '2026-01-02T10:24:36.932965Z'
WHERE "Id" = 3;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260102102437_UpdateBuyerIdToInt_WithDataConversion', '8.0.0');

COMMIT;

START TRANSACTION;

CREATE TABLE outbox_messages (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "EventType" character varying(100) NOT NULL,
    "Payload" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    processed_at timestamp with time zone,
    "RetryCount" integer NOT NULL DEFAULT 0,
    "LastError" text,
    CONSTRAINT "PK_outbox_messages" PRIMARY KEY ("Id")
);

UPDATE "Purchases" SET "CreatedAt" = TIMESTAMPTZ '2026-01-02T14:21:23.671704Z', "PurchaseDate" = TIMESTAMPTZ '2026-01-02T14:21:23.671704Z'
WHERE "Id" = 1;

UPDATE "Purchases" SET "CreatedAt" = TIMESTAMPTZ '2026-01-02T14:21:23.671704Z', "PurchaseDate" = TIMESTAMPTZ '2026-01-02T14:21:23.671704Z'
WHERE "Id" = 2;

UPDATE "Purchases" SET "CreatedAt" = TIMESTAMPTZ '2026-01-02T14:21:23.671704Z', "PurchaseDate" = TIMESTAMPTZ '2026-01-02T14:21:23.671704Z'
WHERE "Id" = 3;

CREATE INDEX idx_outbox_unprocessed ON outbox_messages ("CreatedAt") WHERE "processed_at" IS NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260102142123_AddOutboxMessages', '8.0.0');

COMMIT;

