// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Transport.Data;

#nullable disable

namespace Transport.Migrations
{
    [DbContext(typeof(TransportDbContext))]
    [Migration("20260102141520_search")]
    partial class search
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Transport.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_outbox_unprocessed")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Transport.Entities.TransportEntity", b =>
                {
                    b.Property<int>("TransportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransportId"));

                    b.Property<decimal?>("ActualCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("CarrierId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<string>("DeliveryCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DeliveryCountry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DeliveryStateCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("DeliveryStreet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DeliveryZipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("EstimatedCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PickupCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PickupCountry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PickupStateCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("PickupStreet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PickupZipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScheduleDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TransportId");

                    b.HasIndex("CarrierId");

                    b.HasIndex("DeliveryCity");

                    b.HasIndex("PickupCity");

                    b.HasIndex("PurchaseId");

                    b.HasIndex("ScheduleDate");

                    b.HasIndex("Status");

                    b.ToTable("Transports");

                    b.HasData(
                        new
                        {
                            TransportId = 1,
                            CarrierId = 101,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 15, 20, 169, DateTimeKind.Utc).AddTicks(6659),
                            DeliveryCity = "Los Angeles",
                            DeliveryCountry = "USA",
                            DeliveryStateCode = "CA",
                            DeliveryStreet = "456 Oak Ave",
                            DeliveryZipCode = "90001",
                            EstimatedCost = 150.00m,
                            Notes = "Handle with care - fragile items",
                            PickupCity = "New York",
                            PickupCountry = "USA",
                            PickupStateCode = "NY",
                            PickupStreet = "123 Main St, Warehouse A",
                            PickupZipCode = "10001",
                            PurchaseId = 1001,
                            ScheduleDate = new DateTime(2026, 1, 3, 14, 15, 20, 169, DateTimeKind.Utc).AddTicks(6663),
                            Status = "Pending"
                        },
                        new
                        {
                            TransportId = 2,
                            ActualCost = 215.75m,
                            CarrierId = 102,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 15, 20, 169, DateTimeKind.Utc).AddTicks(6671),
                            DeliveryCity = "Houston",
                            DeliveryCountry = "USA",
                            DeliveryStateCode = "TX",
                            DeliveryStreet = "321 Commerce St, Retail Store",
                            DeliveryZipCode = "77001",
                            EstimatedCost = 220.50m,
                            Notes = "Express delivery required",
                            PickupCity = "Chicago",
                            PickupCountry = "USA",
                            PickupStateCode = "IL",
                            PickupStreet = "789 Industrial Blvd, Distribution Center B",
                            PickupZipCode = "60601",
                            PurchaseId = 1002,
                            ScheduleDate = new DateTime(2026, 1, 4, 14, 15, 20, 169, DateTimeKind.Utc).AddTicks(6673),
                            Status = "InTransit"
                        },
                        new
                        {
                            TransportId = 3,
                            ActualCost = 175.25m,
                            CarrierId = 103,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 15, 20, 169, DateTimeKind.Utc).AddTicks(6675),
                            DeliveryCity = "Seattle",
                            DeliveryCountry = "USA",
                            DeliveryStateCode = "WA",
                            DeliveryStreet = "888 Business Park Dr, Corporate Office",
                            DeliveryZipCode = "98101",
                            EstimatedCost = 180.00m,
                            Notes = "Delivery completed successfully",
                            PickupCity = "Detroit",
                            PickupCountry = "USA",
                            PickupStateCode = "MI",
                            PickupStreet = "555 Factory Rd, Manufacturing Plant",
                            PickupZipCode = "48201",
                            PurchaseId = 1003,
                            ScheduleDate = new DateTime(2026, 1, 1, 14, 15, 20, 169, DateTimeKind.Utc).AddTicks(6677),
                            Status = "Delivered"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
