// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Purchase.Data;

#nullable disable

namespace Purchase.Migrations
{
    [DbContext(typeof(PurchasesDbContext))]
    [Migration("20260102143110_AddOutboxMessages")]
    partial class AddOutboxMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Purchase.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_outbox_unprocessed")
                        .HasFilter("\"processed_at\" IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Purchase.Entities.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("BuyerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("OfferId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Purchases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 25000.00m,
                            BuyerId = 1001,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 31, 10, 422, DateTimeKind.Utc).AddTicks(5388),
                            IsActive = true,
                            OfferId = 1,
                            PurchaseDate = new DateTime(2026, 1, 2, 14, 31, 10, 422, DateTimeKind.Utc).AddTicks(5390),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 32000.00m,
                            BuyerId = 1002,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 31, 10, 422, DateTimeKind.Utc).AddTicks(5393),
                            IsActive = true,
                            OfferId = 2,
                            PurchaseDate = new DateTime(2026, 1, 2, 14, 31, 10, 422, DateTimeKind.Utc).AddTicks(5394),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 18500.00m,
                            BuyerId = 1001,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 31, 10, 422, DateTimeKind.Utc).AddTicks(5395),
                            IsActive = true,
                            OfferId = 3,
                            PurchaseDate = new DateTime(2026, 1, 2, 14, 31, 10, 422, DateTimeKind.Utc).AddTicks(5396),
                            Status = "Processing"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
