// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Purchase.Data;

#nullable disable

namespace Purchase.Migrations
{
    [DbContext(typeof(PurchasesDbContext))]
    partial class PurchasesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Purchase.Entities.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("BuyerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("OfferId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Purchases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 25000.00m,
                            BuyerId = 1001,
                            CreatedAt = new DateTime(2026, 1, 2, 10, 24, 36, 932, DateTimeKind.Utc).AddTicks(9650),
                            IsActive = true,
                            OfferId = 1,
                            PurchaseDate = new DateTime(2026, 1, 2, 10, 24, 36, 932, DateTimeKind.Utc).AddTicks(9651),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 32000.00m,
                            BuyerId = 1002,
                            CreatedAt = new DateTime(2026, 1, 2, 10, 24, 36, 932, DateTimeKind.Utc).AddTicks(9656),
                            IsActive = true,
                            OfferId = 2,
                            PurchaseDate = new DateTime(2026, 1, 2, 10, 24, 36, 932, DateTimeKind.Utc).AddTicks(9656),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 18500.00m,
                            BuyerId = 1001,
                            CreatedAt = new DateTime(2026, 1, 2, 10, 24, 36, 932, DateTimeKind.Utc).AddTicks(9658),
                            IsActive = true,
                            OfferId = 3,
                            PurchaseDate = new DateTime(2026, 1, 2, 10, 24, 36, 932, DateTimeKind.Utc).AddTicks(9659),
                            Status = "Processing"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
